### ISSUE TITLE
Is `--filesystem=host` needed or just `--filesystem=home`?

### ISSUE THREAD

**Issue by travier** [flathub/org.octave.Octave#208]
See details in https://www.man7.org/linux/man-pages/man5/flatpak-metadata.5.html#FILE_FORMAT.

As far as I understand, Octave only needs access to the content in the user home dir and not the full host filesystem.

**Comment by vchernin** [comment]
in an ideal world, the filechooser portal should be enough, but it won't be if you need drag and drop (filetransfer portal is barely implemented anywhere).

**Comment by travier** [comment]
Sure, I'm not suggesting you remove the access entirely, just that you restrict it to the home dir.

**Comment by mtmiller** [comment]
Strictly speaking, Octave doesn't need access to any filesystems, but this is provided as a service to the user. Since Octave is a flexible development environment, users like to be able to open files, link libraries, and run programs from anywhere on the host filesystem.

If there is a compelling reason to restrict the default filesystem access, then we can certainly comply.

**Comment by travier** [comment]
Alright, seems like a valid reason.
