### ISSUE TITLE
Incorrect bug tracker link on flathub package page

### ISSUE THREAD

**Issue by apjanke** [flathub/org.octave.Octave#46]
Hi, Octave flathub maintainers,

On the flathub GNU Octave page at https://flathub.org/apps/details/org.octave.Octave, the link to the Octave issue tracker (the "Issues" button near the bottom of the page) is incorrect. It is currently https://bugs.octave.org/, but that site is nonfunctional. It should be something like https://savannah.gnu.org/bugs/?group=octave.

**Comment by mtmiller** [comment]
The link comes directly from the AppStream metadata maintained within Octave, so isn't a flatpak packaging issue.

IMHO the link is correct, the real issue is https://savannah.gnu.org/bugs/?55402. Assuming the redirect gets fixed, the link https://bugs.octave.org/ is the preferred canonical URL for the bug tracker.
